services:
  tipddns:
    image: jmdirksen/tipddns:latest
    environment:
      LOGINNAME: myusername
      PRIVATEKEY: -----BEGIN PRIVATE KEY----- ... -----END PRIVATE KEY-----
      DOMAIN: mydomain.com
      RECORD: @
      TTL: 300
      TYPE: A
      INTERVAL: 300
    restart: unless-stopped
